//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KampanjDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kampanj
    {
        public int Id { get; set; }
        public string VardeKod { get; set; }
        public int Bonuspoang { get; set; }
        public System.DateTime StartDatum { get; set; }
        public System.DateTime SlutDatum { get; set; }
    }
}
